# fly.toml app configuration file generated for istartx-upload on 2025-10-06T00:00:00Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "istartx-upload"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  PORT = "3000"

[[mounts]]
  source = "uploads_data"
  destination = "/app/uploads"