# fly.toml app configuration file generated for istartx-upload on 2025-10-06T00:00:00Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# Global multi-region upload service deployment

app = "istartx-upload-demo"
primary_region = "fra"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

# Multi-region configuration
# Machines deployed in: FRA, SJC, DFW, AMS, LAX, CDG, ORD, SIN, ARN
# Each with 2GB volume for upload storage

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

[env]
  PORT = "3000"

[[mounts]]
  source = "uploads_data"
  destination = "/app/uploads"
  size_gb = 2